### ISSUE TITLE
XML hierarchical display on left side of editor

### ISSUE THREAD

**Issue by digitalkg** [culibraries/geoDataLoader#13]
Can the XML/metadata on the left side be previewed in a hierarchical structure? (like the ETD reviewer?) This will help us read the file and locate metadata that isn't importing correctly or was placed in an odd field.

**Comment by mbstacy** [comment]
Agree this would be nice to quickly find the information needed.

**Comment by mbstacy** [comment]
@digitalkg I have added a styled viewer in which you can collapse/expand nodes and hopefully view objects.
