### ISSUE TITLE
Data loader throws error

### ISSUE THREAD

**Issue by erikradio** [culibraries/geoDataLoader#14]
Couldn't figure out why but the loader is throwing an error for this one 

https://drive.google.com/open?id=1RGBMy01C53_qJyIX2PzQ0YepYZqcimBv

Note: i unzipped, removed top level folder, and rezipped contents before uploading

**Comment by mbstacy** [comment]
@erikradio First encoding error. On the translation on a few items was using a string which was trying to decode to ASCII. I have fixed the error but will continue to double check to make sure all is in Unicode (UTF-8).  Please try the file again. I also tried and still see the `object` as the title. Working on issues today. Please let me know if this closes the issue.

**Comment by mbstacy** [comment]
@erikradio I going to close the issue. If you believe that this issue has not been resolved. Please comment!

**Comment by erikradio** [comment]
just confirming this worked for me too
